# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     serviceUrl:
#       # defaultZone: http://127.0.0.1:8761/eureka/
#       defaultZone: ${EUREKA_SERVER_ADDRESS:http://127.0.0.1:8761/eureka}
# instance:
#   prefer-ip-address: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-75105354.okta.com/oauth2/default
    audience: api://default
