eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://127.0.0.1:8761/eureka/}
instance:
  prefer-ip-address: true

okta:
  oauth2:
    issuer: https://dev-75105354.okta.com/oauth2/default
    audience: api://default
